"""
File: trading_settings.py
Project: AutoT

Purpose:
    Central trading and risk configuration for AutoT.
"""


ACCOUNT_SIZE = 10000
RISK_PER_TRADE = 1.0

MAX_OPEN_POSITIONS = 5
MAX_PORTFOLIO_RISK_PERCENT = 5.0
MAX_DAILY_LOSS_PERCENT = 3.0

DEFAULT_STOP_LOSS_PERCENT = 2.0
DEFAULT_TAKE_PROFIT_PERCENT = 4.0
MIN_CONFIDENCE = 55.0